### ISSUE TITLE
error on npm run start and build

### ISSUE THREAD

**Issue by bq1028** [loteoo/hyperapp-boilerplate#1]
Hi ,
Could you please help troubleshoot for the error below,  thank you in advance!

root@8f99f95961ea:/app/hyperapp-boilerplate# npm run start
> hyperapp-boilerplate@1.0.0 start /app/hyperapp-boilerplate
> parcel src/index.html --out-dir public
Server running at http://localhost:1234 
🚨  /app/hyperapp-boilerplate/src/index.html: Cannot resolve dependency '/app/hyperapp-boilerplate/src/assets/icon-512x512.png' at '/app/hy
perapp-boilerplate/src/assets/icon-512x512.png'
    at Resolver.resolve (/app/hyperapp-boilerplate/node_modules/parcel-bundler/src/Resolver.js:69:17)

**Comment by loteoo** [comment]
Oops, there was an invalid link in the <head>, (parcel resolved on my machine via cache)

It's fixed now, thanks for pointing it out!
